# action.yml
name: 'Publish AUR package'
description: 'Publish an AUR package'
author: KSXGitHub
branding:
  color: blue
  icon: package
inputs:
  pkgname:
    description: 'AUR package name'
    required: true
  pkgbuild:
    description: 'Path to PKGBUILD file'
    required: true
  commit_username:
    description: 'The username to use when creating the new commit.'
    required: true
  commit_email:
    description: 'The email to use when creating the new commit.'
    required: true
  ssh_private_key:
    description: 'Your private key with access to AUR package.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
