name: 'Publish AUR package'
description: 'Publish an AUR package'
author: KSXGitHub
branding:
  color: blue
  icon: package
inputs:
  pkgname:
    description: 'AUR package name'
    required: true
  pkgbuild:
    description: 'Path to PKGBUILD file'
    required: true
  assets:
    description: 'Newline-separated glob patterns for additional files to be added to the AUR repository'
    required: false
    default: ''
  updpkgsums:
    description: 'Update checksums using `updpkgsums`'
    required: false
    default: 'false'
  test:
    description: 'Check that PKGBUILD could be built'
    required: false
    default: 'false'
  test_flags:
    description: 'Command line flags for makepkg to build the package (if `test` is enabled)'
    required: false
    default: '--clean --cleanbuild --nodeps'
  post_process:
    description: 'A line of commands to execute after processing the package'
    required: false
    default: ''
  commit_username:
    description: 'The username to use when creating the new commit'
    required: true
  commit_email:
    description: 'The email to use when creating the new commit'
    required: true
  ssh_private_key:
    description: 'Your private key with access to AUR package.'
    required: true
  commit_message:
    description: 'Commit message to use when creating the new commit'
    required: false
    default: 'Update PKGBUILD and .SRCINFO with GitHub Actions'
  allow_empty_commits:
    description: 'Allow empty commits, i.e. commits with no change.'
    required: false
    default: 'true'
  force_push:
    description: 'Use --force when push to the AUR.'
    required: false
    default: 'false'
  ssh_keyscan_types:
    description: 'Comma-separated list of types to use when adding aur.archlinux.org to known hosts'
    required: false
    default: 'rsa,dsa,ecdsa,ed25519'
  update_pkgver:
    description: "Run `makepkg -od` to update `pkgver`. Requires that the `pkgver()` function defined in the `PKGBUILD` file doesn't required any dependencies other than git"
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
