# action.yml
name: 'Publish AUR package'
description: 'Publish an AUR package'
author: KSXGitHub
branding:
  color: blue
  icon: package
inputs:
  filename:
    description: File to import
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
